# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinfo',
            name='tshow',
            field=models.CharField(default='', max_length=20),
        ),
    ]
