# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20180210_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinfo',
            name='tbanner',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
