# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0005_typeinfo_tbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='typeinfo',
            name='tcommend1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commend1', to='df_goods.GoodsInfo'),
        ),
        migrations.AddField(
            model_name='typeinfo',
            name='tcommend2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commend2', to='df_goods.GoodsInfo'),
        ),
        migrations.AddField(
            model_name='typeinfo',
            name='tcommend3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commend3', to='df_goods.GoodsInfo'),
        ),
    ]
