# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0006_auto_20180210_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gbig_pic',
            field=models.ImageField(default='', upload_to='df_goods'),
            preserve_default=False,
        ),
    ]
