# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0007_goodsinfo_gbig_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gwarning',
            field=models.IntegerField(default=50),
        ),
    ]
