# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0008_goodsinfo_gwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo'),
        ),
        migrations.AddField(
            model_name='slide',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo'),
        ),
    ]
