# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0010_auto_20180210_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='aalt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adv',
            name='atitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
