# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0011_auto_20180210_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='up_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
