# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0012_goodsinfo_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='up_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
