# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nikename',
            field=models.CharField(default='', max_length=20),
        ),
    ]
