# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_userinfo_nikename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
