# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_userinfo_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('postcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('parea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='df_user.AreaInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uaddress',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ushou',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uyoubian',
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county', to='df_user.AreaInfo'),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='default_addr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_addr', to='df_user.AddressInfo'),
        ),
    ]
