# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0004_auto_20180213_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinfo',
            name='county',
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town', to='df_user.AreaInfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='default_addr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_user', to='df_user.AddressInfo'),
        ),
    ]
