# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0005_auto_20180213_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areainfo',
            old_name='area',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='town',
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='df_user.AreaInfo'),
        ),
    ]
