# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-11 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0002_userinfo_nikename'),
        ('df_goods', '0011_auto_20180210_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='实付')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='运费')),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=11)),
                ('receiver', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已付款'), (2, '已发货'), (3, '已收货'), (4, '已完成')])),
                ('isDelete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_order.Order')),
            ],
        ),
    ]
