# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0002_auto_20180211_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
