# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0007_auto_20180213_0714'),
        ('df_order', '0003_auto_20180211_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='df_user.AddressInfo'),
        ),
    ]
