# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-14 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0004_order_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='df_user.AreaInfo'),
        ),
    ]
